services:
  lf-slam-dev:
    container_name: lf-slam-dev
    build:
      context: .
      args:
        C_USER: ${USER}
        C_UID: ${UID}
        C_GID: ${GID}
    image: lf-slam-dev:latest
    stdin_open: true
    tty: true
    volumes:
      - ${HOME}/dev/projects/robotics/lf_slam:/home/${USER}/lf_slam
      - ${HOME}/dev/shared/data:/home/${USER}/data:rw
      - ${HOME}/.ssh:/home/${USER}/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/${USER}/lf_slam
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    restart: unless-stopped
    network_mode: host
